[project]
name = 'genetrust-stacks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dataset-registry]
path = 'contracts/genetic-data.clar'
clarity_version = 3
epoch = 3.0

[contracts.dataset-registry-trait]
path = 'contracts/dataset-registry-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.exchange]
path = 'contracts/exchange.clar'
clarity_version = 3
epoch = 3.0

[contracts.attestations]
path = 'contracts/attestations.clar'
clarity_version = 3
epoch = 3.0

[contracts.data-governance]
path = 'contracts/data-governance.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
